"""
Lesson data for M1, M2, M3, M4 - extracted and formatted
This file is generated by extract_m1_m2_m3_m4_lessons.py
"""
import json

# Import the lesson data
exec(open('scripts/m1_m2_m3_m4_lessons.txt').read())

